name: Porfolio Refresh DATA JSON 

on:
    push:
        branches:
            - main
            
    schedule:
        - cron: '0 0 */2 * *'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repositorio
              uses: actions/checkout@v2

            - name: Fazendo setup no Node.js
              uses: actions/setup-node@v1
              with:
                node-version: 20
                
            - name: Instalando as dependencias
              run: 
                npm ci
              
            - name: Rodando o codigo
              run:
                node src/axios-get-repos.js
              env:
                  GITHUB_TOKEN: ${{secrets.TOKEN_GITHUB}}
                  GITHUB_USERNAME: ${{secrets.USERNAME_GITHUB}}

            - name: Fazendo o commit dos novos dados
              run: 
                git config --local user.email "action@github.com"
                git config --local user.name "GitHub Action"
                git add data/repositorios-data.json
                git commit -m "Atualizando o arquivo de dados JSON"
                git push
