name: Porfolio Refresh DATA JSON 

on:
    schedule:
        - cron: '0 0 */2 * *'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                node-version: 20
            - run: npm ci
            - run: npm run start